<?php

/**
 * @file
 * Defines the default hooks that the history js module implements.
 */

/**
 * Implements hook_permission().
 *
 * @return
 *  A Drupal hook_permission keyed array
 */
function isotope_permission() {
  return array(
    'administer isotope' => array(
      'title' => t('Administer Isotope JS'),
      'description' => t('Set configuration options for Isotope.js'),
    ),
  );
}

/**
 * Implements hook_menu().
 *
 * Defines the admin settings page for the module
 *
 * @return
 *   a Drupal menu_item array that references the system form in the inc file
 */
function isotope_menu() {
  $items['admin/config/isotope'] = array(
    'title' => 'Isotope.js Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('isotope_admin'),
    'access callback' => 'user_access',
    'access arguments' => array('access administer isotope'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/isotope.admin.inc'
);
  return $items;
}

/**
 * Implements hook_init().
 *
 * Checks for conflicts, and displays warnings if they are detected
 * Adds the configured library javascript to the site
 */
function isotope_init() {
  drupal_add_library('isotope', 'jquery.isotope', TRUE);
}

/**
 * Implements hook_library().
 *
 * Checks to see if the Library exists, and makes it available
 * with the settings configured by the admin_settings form
 *
 * @return
 *   Drupal Library definition for History.js
 */
function isotope_library() {
  $libraries       = array();
  $libpath         = libraries_get_path('isotope');
  $jspath = array();
  $jspath['jquery.isotope']        = $libpath.'/jquery.isotope.min.js';
  $jspath['jquery.infinitescroll'] = $libpath . '/js/jquery.infinitescroll.min.js';
  $jspath['jquery.bbq']        = $libpath . '/js/jquery.ba-bbq.min.js';
  $jspath['isotope.jquery']        = $libpath . '/js/jquery-1.6.4.min.js';
  $dependencies = array();
  $settings     = variable_get('isotope_settings',array());
  $useisobbq    = !empty($settings['jquery.ba-bbq']); 
  $useisoscroll = !empty($settings['jquery.infinitescroll']);

  $libraries['jquery.isotope'] = array(
    'title'   => 'David Desandro\'s Isotope.js',
    'website' => 'https://github.com/desandro/isotope/',
    'version' => '1.5.03',
    'js'      => array($jspath['jquery.isotope'] => array()),
    'dependencies' => array(
    ),
  );

  $libraries['jquery.infinitescroll'] = array(
    'title'   => 'David Desandro\'s Isotope.js',
    'website' => 'https://github.com/desandro/isotope/',
    'version' => '2.0b2.110713',
    'js'      => array($jspath['jquery.infinitescroll'] => array())
    );

  $libraries['jquery.bbq'] = array(
     'title'   => 'jQuery BBQ',
     'website' => 'http://benalman.com/projects/jquery-bbq-plugin/',
     'version' => '1.2.1',
     'js'      => array($jspath['jquery.bbq'] => array())
  );

  if($useisoscroll) {
    $libraries['jquery.isotope']['dependencies'][] = array('isotope','jquery.infinitescroll');
  }

  if($useisobbq) {
    $libraries['jquery.isotope']['dependencies'][] = array('system','jquery.bbq');
  }

  return $libraries;
}
/**
 * Implements hook_library_alter();
 */
function isotope_library_alter(&$libraries, $module) {
  module_load_include('module', 'libraries');  
  $libpath   = libraries_get_path('isotope');  
  $settings  = variable_get('isotope_settings', array());
  $useisobbq = !empty($settings['jquery.ba-bbq']); 
  $useisojq  = !empty($settings['jquery-1.6.4']);
  
  if(is_dir($libpath) != TRUE) {
    
    if($useisobbq && $module == 'system' && isset($libraries['jquery.bbq'])) {
      $bbqpath = $libpath . '/js/jquery.ba-bbq.min.js';
      $libraries['jquery.bbq']['version'] = '1.2.1-isotope';
      $libraries['jquery.bbq']['js'] = array($bbqpath => array());
    }
  
    if($useisojq && $module == 'system' && isset($libraries['jquery'])) {
      $jqpath = $libpath . '/js/jquery-1.6.4.min.js';
      $libraries['jquery']['version'] = '1.6.4-isotope';
      $oldsettings = array();
      if(isset($libraries['jquery']['js']['misc/jquery.js'])){
        $oldsettings = $libraries['jquery']['js']['misc/jquery.js'];
      }
      $libraries['jquery']['js'] = array($jqpath => $oldsettings );
    }
  }
}

